# Generated by Django 4.2.7 on 2023-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='titel',
            field=models.CharField(choices=[('Part Time', 'Part time'), ('Full Time', 'Full Time')], max_length=100),
        ),
    ]
