# Generated by Django 4.2.7 on 2023-11-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_job_type_alter_job_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
