# Generated by Django 4.2.7 on 2024-01-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_catogery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catogery',
            options={'verbose_name_plural': 'Catogeries'},
        ),
    ]
